---
    # Filepaths
    PAINT_TRAIN_PATH: "datasets/vangogh2photo/trainA"
    PHOTO_TRAIN_PATH: "datasets/vangogh2photo/trainB"
    PAINT_TEST_PATH: "datasets/vangogh2photo/testA"
    PHOTO_TEST_PATH: "datasets/vangogh2photo/testB"
    MONITOR_IMAGE_FILEPATH: "training/train_imgs"
    CHECKPOINT_FILEPATH: "training/model_ckp/cgan_ckpts.{epoch:03d}"
    FINAL_WEIGHTS_PATH: "saved_models/vg2photo-2020-12-31/model_weights/vg2p-2020-12-31"
    INF_IMG_PATH:  "saved_models/vg2photo-2020-12-31/inference_images/"

    # General parameters
    SAVE_FORMAT: 'tf'
    
    #Callbacks
    MONITOR: False
    CKPTS: True
    TENSORBOARD: False
    TBOARD_LOGDIR: "logs/fit/"

    # Model parameters
    INPUT_SHAPE: 
        - 256
        - 256
        - 3
    DISCRIM_LR: 0.0002
    DISCRIM_BETA: 0.5     
    GEN_LR: 0.0002
    GEN_BETA: 0.5
    EPOCHS: 200
    LR_SCHEDULE: True
    DECAY_START: 100



